[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=--ld-path=wild"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[build]
rustc-wrapper = "sccache"
rustflags = ["-Z", "threads=8"]

[unstable]
gc = true
build-std = ["std", "panic_abort", "core"]
build-std-features = ["panic_immediate_abort"]
