when:
  event: tag
  ref: refs/tags/v*

steps:
  build:
    image: debian:sid-slim
    commands:
      - apt-get update
      - apt-get install -y curl libxkbcommon-dev mold build-essential lld clang llvm
      - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustup toolchain install nightly
      - rustup default nightly
      - rustup target add x86_64-pc-windows-msvc
      - cargo install cargo-xwin cargo-pgo
      - cd text_editor
      - mkdir target
      - cp -r pgo-profiles target
      - cargo pgo optimize
      - mv target/x86_64-unknown-linux-gnu/release/fabseeditor ../fabseeditor_${CI_COMMIT_TAG}
      - cargo xwin build --target x86_64-pc-windows-msvc --release
      - mv target/x86_64-pc-windows-msvc/release/fabseeditor.exe ../fabseeditor_${CI_COMMIT_TAG}.exe

  release:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      file_exists: overwrite
      files:
        - "fabseeditor_${CI_COMMIT_TAG}"
        - "fabseeditor_${CI_COMMIT_TAG}.exe"
      checksum: sha256
      api_key:
        from_secret: FABSEGIT_RELEASE
      target: master
      title: Fabseeditor ${CI_COMMIT_TAG} 
      draft: true
