when:
  event: push
  branch: main

steps:
  build:
    image: debian:sid-slim
    commands:
      - apt-get update
      - apt-get install -y sccache curl libxkbcommon-dev libgtk-3-dev mold build-essential
      - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustup toolchain install nightly
      - rustup default nightly
      - rustup target add x86_64-pc-windows-gnu
      - cd text_editor
      - cargo build --release
      - ls target
      - ls target/release
      - cargo build  --release --target x86_64-pc-windows-gnu
      - ls target 
      - ls target/release

  release:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      file_exists: overwrite
      files:
        - "fabseapp_${CI_COMMIT_TAG}_amd64.deb"
        - "fabseapp_${CI_COMMIT_TAG}_amd64.AppImage"
        - "fabseapp_${CI_COMMIT_TAG}_x64-setup.exe"
      checksum: sha256
      api_key:
        from_secret: FABSEGIT_RELEASE
      target: master
      title: Fabseapp ${CI_COMMIT_TAG} 
      draft: true
